config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  post '/edit_image' => 'home#edit_image', :as => :edit_image

  get '/show_image' => 'home#show_image', :as => :show_image

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def edit_image

    file_path = params[:uploaded_data_file][:photo].path

    # execute python script
    @image = `python3 lib/assets/python/edit_image.py "#{file_path}"`

    redirect_to show_image_path(image: @image)
  end

  def show_image
    @image = params[:image].split("\n").last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Edit Image:</h1>

<h2>Test Python Integration</h2>

<br>
<div>
	<%= render :partial => 'partials/form' %>
</div>


<div class="loader" style="display: none;position: absolute;left: 50%;top: 35%;"></div>
<script type="text/javascript">
	document.querySelector("#myForm").addEventListener("submit", function(e){
		document.getElementsByClassName('loader')[0].style.display = 'block';
	});
</script>

app/views/home/show_image.html.erb
<h1>Edit Image:</h1>
<%= link_to 'Back', :back %>

<br>
<div class='image-tag'>
	<%= image_tag @image.split("\n").last, class: "img-responsive" %>
</div>
<style>
	body {
		background: burlywood;
	}
	.image-tag {
		max-width: 500px;
	}
	.img-responsive {
	    width: 100%;
	}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RemoveBg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <p class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>

    <%= yield %>
  </body>
</html>

app/views/partials/_form.html.erb
<%= form_for(:uploaded_data_file, :url => edit_image_path , :remote => true, :html => {  id: "myForm", :multipart => true } ) do |f| %>
  <%= f.label "Upload" %><br />
  <%= f.file_field :photo, accept: 'image/png,image/jpeg' %>

  <%= f.button 'Image Edit'.html_safe, type: :submit, id: 'submit_btn', data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Image Processing..." } %>
<% end %>

app/views/partials/_images.html.erb
_images.html.erb